{% set name = "django-colorfield" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5624a23e2fe97066f45e56eedf9672ab545aa5e52a790cfc33a5f29160a70684

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - django

test:
  imports:
    - colorfield

about:
  home: https://pypi.org/project/jsonLookup/
  summary: django-colorfield, simple color field for your models with a nice color-picker in the admin-interface.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
