{% set name = "django-colorfield" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 670ef72ded093360c9781fedd33d9ead267b34481139d4ab240dfacea5cf0abf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - django

test:
  imports:
    - colorfield

about:
  home: https://pypi.org/project/jsonLookup/
  summary: django-colorfield, simple color field for your models with a nice color-picker in the admin-interface.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
