{% set name = "django-colorfield" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63a542c417b72d0dac898a0f61a2a00aed3c9aabc2f5057c926efccf421f7887

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - django

test:
  imports:
    - colorfield

about:
  home: https://pypi.org/project/jsonLookup/
  summary: django-colorfield, simple color field for your models with a nice color-picker in the admin-interface.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
